### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by ftonello** [WeAreROLI/guidelines#5]
Why don't we have this in a wiki page instead of a repository?

**Comment by lpil** [comment]
* This isn't project specific
* Repos are easier to version than wikis
* Wikis are not at all suited for storing config files

Even with text based documentation for one project what makes it better than markdown files in a `docs` directory? Then it's versioned with the project, can be accessed offline, and you can be more flexible with what formats you use.

**Comment by ftonello** [comment]
* Yes, and we are using google docs for documentation. I don't really like it but it's what we get.
* Right, but what's the need to version this?
* That's true, wikis and others are just for text, but that's why we have google drive and others.

**Comment by lpil** [comment]
> Yes, and we are using google docs for documentation. I don't really like it but it's what we get.

We can change that. :)

> Right, but what's the need to version this?

It's config files.

> That's true, wikis and others are just for text, but that's why we have google drive and others.

Still bad for config files, and really hard to access programatically.

**Comment by ftonello** [comment]
We don't really need a repo for that. Who cares about old versions of a config file? We could use btsync then, it's what we use for samples file (although in that case we will switch to a repository because we actually need to be versioned).

BTW: How did you reply in-lined?

**Comment by lpil** [comment]
True, we don't *need* a repo, but GH is a tool we already use, public repos are free, and activity makes us look good. Especially if we're showing off our standards, etc.

GH comments use markdown:

```
> This is a quote

This is regular text
```

:)

**Comment by ftonello** [comment]
Fair enough. :)

**Comment by lpil** [comment]
:dancer: Thanks Felipe! :)
